### ISSUE TITLE
Licensing changes / Opencollective discussion

### ISSUE THREAD

**Issue by SimonCropp** [NServiceBusExtensions/Home#1]
For discussing Proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org: https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org/

**Comment by ValdisThomann** [comment]
Not a big deal, but the link on open collective for adding your name to backers.md is wrong. It is currently `https://github.com/NServiceBusExtensions/Home/blob/master/backers.md` but it should be `https://github.com/NServiceBusExtensions/Home/blob/master/src/backers.md`

**Comment by SimonCropp** [comment]
@ValdisThomann fixed.
